apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: helloworldui-autoscaler
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: helloworld-ui
  targetCPUUtilizationPercentage: 50
