apiVersion: v1
kind: Pod
metadata:
  name: volume-example
spec:
  containers:
    - name: nginx
      image: nginx:stable-alpine
      ports:
        - containerPort: 80
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
    - name: content
      image: alpine:latest
      volumeMounts:
        - name: html
          mountPath: /html
      command: ["/bin/sh", "-c"]
      args:
        - while true; do
          echo $(date)"<br />" >> /html/index.html;
          sleep 5;
          done
  volumes:
    - name: html
      persistentVolumeClaim:
        claimName: pvc-sc-example

## local port-forward
# kubectl port-forward pod/volume-example 8080:80 &
# curl localhost:8080
# after restart should contain old time entries
