# Number of replicas to run by default
replicaCount: 1

image:
  repository: paulbouwer/hello-kubernetes
  tag: 1.5

# Defines what the hello-kubernetes application should display
message: "I just deployed this on Kubernetes!"

# Deploy a HPA which scales the hello-kubernetes deployment
hpa:
  # If disabled, no HPA must be deployed
  enabled: true
  minReplicas: 1
  maxReplicas: 25
  targetCPUUtilizationPercentage: 50

resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi
