---
apiVersion: v1
kind: Service
metadata:
  name: redmine
spec:
  type: LoadBalancer
  ports:
    # TODO: Make functional
  selector:
  # TODO: Make functional
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
spec:
  selector:
    matchLabels:
    # TODO: Make functional
  replicas: 1
  template:
    metadata:
      labels:
      # TODO: Make functional
    spec:
      containers:
      - name: redmine
        image: docker.io/bitnami/redmine:4.0.0
        env:
        # TODO: Make functional
        ports:
        # TODO: Make functional
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 1
