kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-selector-example
  labels:
    type: host-pv
spec:
  #overwrite the to use NO storage class
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    type: DirectoryOrCreate
    path: "/tmp/mypvselector"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-selector-example
spec:
  #overwrite the to use NO storage class
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: hostpath

