apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-lb
spec:
  type: LoadBalancer
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-kubernetes
