apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:green
        name: my-container
        ports:
          - containerPort: 8080
            hostPort: 80
            name: http
        env:
          - name: TEST
            value: "loodse"
        resources:
            requests:
              memory: "64Mi"
              cpu: "250m"