apiVersion: v1
kind: Secret
metadata:
  name: my-secret
stringData:
  secret: value-xxx
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - image: alpine
    name: env-printer
    command:
      - /bin/sh
      - -c
      - "cat /opt/my-volume/secret && sleep 10 && echo 'now' && sleep 99d"
    volumeMounts:
      - name: my-volume-name
        mountPath: /opt/my-volume
        readOnly: true
  volumes:
    - name: my-volume-name
      secret:
        secretName: my-secret
