apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  hello: world
  hello2: hello Loodsians
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - image: alpine
    name: env-printer
    command:
      - /bin/sh
      - -c
      - "echo $my_env_var && sleep 99d"
    env:
      - name: my_env_var
        valueFrom:
          configMapKeyRef:
            name: my-configmap
            key: hello

