apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
spec:
  containers:
    - image: nginx
      name: my-nginx
    ### optional side car (with debug tools)
    - image: nicolaka/netshoot
      name: debug
      command: ["bash","-c", "ping my-nginx"]
