apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs-2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-app
      version: v2
  template:
    metadata:
      labels:
        app: my-app
        version: v2
    spec:
      containers:
      - image: loodse/demo-www
        name: loodse-www
        ports:
          - containerPort: 80
            name: http