apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
      version: v1
  template:
    metadata:
      labels:
        app: my-app
        version: v1
    spec:
      containers:
      - image: nginx
        name: my-container
        ports:
          - containerPort: 80
            name: http
        env:
          - name: TEST
            value: "loodse"
        resources:
            requests:
              memory: "64Mi"
              cpu: "250m"