apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-app
  name: test
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: my-app
  type: LoadBalancer
