apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-deployment
  # use replica set definition
  template:
    metadata:
      labels:
        app: test-deployment
    spec:
      containers:
        - image: helloworld
          name: helloworld