apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaler
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: my-deployment
  targetCPUUtilizationPercentage: 50

## 1. Create Deployment and matching service

## 2. Apply above HPA

## 3. Create load
# kubectl run -i --tty load-generator2 --image=alpine/bombardier -- -c 200 -d 100s -l http://web.default.svc.cluster.local