apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  hello: world
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - image: an-image
    name: env-printer
    command:
      - /bin/sh
      - -c
      - "echo $my_env_var && sleep 99d"
    env:
      - name: my-env-var
        valueFrom:
          configMapKeyRef:
            key: a-key
            name: a-configmap

