apiVersion: v1
kind: Secret
metadata:
  name: my-secret
stringData:
  secret: value
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - image: an-image
    name: env-printer
    command:
      - /bin/sh
      - -c
      - "cat /opt/my-volume/secret-key-name && sleep 99d"
    volumeMounts:
      - name: volume-name
        mountPath: /opt/my-volume
  volumes:
    - name: my-volume-name
      secret:
        secretName: the-secret
