apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: my-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: another-app
    spec:
      containers:
      - image: my-image
        name: my-container
